name: vpn_app
description: "A beautiful VPN application made with Flutter"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  get_it: ^8.0.3
  go_router: ^14.7.1
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.17
  intl_phone_field: ^3.2.0
  country_picker: ^2.0.27
  hugeicons: ^0.0.7
  intl: ^0.20.2
  logger: ^2.5.0
  lottie: ^3.3.1
  dio: ^5.8.0+1
  mime: ^2.0.0
  http_parser: ^4.1.2
  shared_preferences: ^2.5.2
  cached_network_image: ^3.4.1
  http: ^1.4.0
  geolocator: ^9.0.2
  country_icons: ^3.0.0
  flaticon: ^0.0.1
  permission_handler: ^12.0.0+1
  flutter_local_notifications: ^19.2.1
#  openvpn_flutter: ^1.3.4
  url_launcher: ^6.3.1
  flutter_contacts: ^1.1.9+2
  flutter_v2ray: ^1.0.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/ovpn_configuration/vpngate_219.100.37.196_tcp_443.ovpn
    - assets/ovpn_configuration/
    - assets/ovpn_configuration/Server1-TCP443.ovpn
    - assets/ovpn_configuration/certs/ca.crt
    - assets/ovpn_configuration/certs/client.crt
    - assets/ovpn_configuration/certs/client.key
    - assets/ovpn_configuration/vpnbook-ca149-tcp443.ovpn